name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab=4.0.0
  - seaborn
  - pandas=2.0.1 
  - pip=23.1.2 
  - pandas-profiling
  - pyarrow=11.0.0 
  - pip:
      - wandb==0.15.3